### ISSUE TITLE
Error on running short code

### ISSUE THREAD

**Issue by AR3S-Vega** [ozanerhansha/qRNG#7]
Here is the short code. I just want to generate some QRNGs for a small project.

```
import qrng

for i in range(100):
    print(qrng.get_random_int(0,9))
```

Traceback (most recent call last):
  File "C:\Users\[USER]\Documents\python\qrngarraymakaer.py", line 4, in <module>
    print(qrng.get_random_int(0,9))
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python37\lib\site-packages\qrng\__init__.py", line 77, in get_random_int
    result = int(get_bit_string(n),2)
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python37\lib\site-packages\qrng\__init__.py", line 67, in get_bit_string
    _request_bits(n-len(_bitCache))
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python37\lib\site-packages\qrng\__init__.py", line 60, in _request_bits
    job = qiskit.execute(_circuit, _backend, shots=1)
NameError: name '_backend' is not defined

**Comment by JiihwanKim** [comment]
Before generating random numbers, you need to set the backend.
Please refer to the tutorial.
